### ISSUE TITLE
Error at $my.Note trim?

### ISSUE THREAD

**Issue by joaociocca** [iRon7/Log-Entry#1]
I'm getting an error on this line:
`$My.Notes -Split("\r\n") | ForEach {$Note = $_ -Split(":", 2); If ($Note[0].Trim()) {$My[$Note[0].Trim()] = $Note[1].Trim()}}`
Whenever I try to run, it runs ok, but there's an error message:
"Error at 259,86: Não é possível chamar um método em uma expressão de valor nulo."
translates to "not possible to call method in expression of null value"

**Comment by iRon7** [comment]
Hello João,

 

Apparently there are some **.Note** headers that can cause this.

I have updated my Log-Entry framework to 02.01.04 to prevent this.

 

Best regards,

Ronald
