### ISSUE TITLE
How to use the Debug flag?

### ISSUE THREAD

**Issue by gostega** [iRon7/Log-Entry#12]
I've tried running .\myscript.ps1 -debug but it doesn't seem to show debug lines in the logfile.
Can't see any examples in the readme. Not sure what I'm doing wrong.
Thanks for your help!

**Comment by iRon7** [comment]
` .\myscript.ps1 -debug` is supposed to write all the usual log entries *plus* the log entries that are invoked with `Write-debug`, e.g.:


```PowerShell
Log-Debug "Password:" $Password "(This will not be shown and captured unless the common -Debug argument is supplied)"
```

**Comment by gostega** [comment]
Hi Ron,
Yes that's what I'm doing. I just stripped everything out of my script except the Log-Entry framework and a Main function with acouple of lines, and .\myscript.ps1 -debug does not output the test line I included.

I'll try again and let you know.
P.S. have you had a chance to look at my pull request with the line number changes?

**Comment by gostega** [comment]
For anyone else who comes across this thread, I found my problem, I was missing [CmdletBinding()] in front of my param block.
