### ISSUE TITLE
Setting -Preserve 0 turns off Divider

### ISSUE THREAD

**Issue by Ravynne** [iRon7/Log-Entry#4]
It looks like the line of code in the function Set-LogFile to print the divider is one block too high. If placed one block lower, then the divider will print in cases where Preserve is set to 0.

`		If ((Test-Path($Location)) -And $Preserve) {
			$My.Log.Length = (Get-Item($Location)).Length 
			If ($My.Log.Length -gt $Preserve) {									# Prevent the log file to grow indefinitely
				$Content = [String]::Join("`r`n", (Get-Content $Location))
				$Start = $Content.LastIndexOf("`r`n$Divider`r`n", $My.Log.Length - $Preserve)
				If ($Start -gt 0) {Set-Content $Location $Content.SubString($Start + $Divider.Length + 4)}
			}
		}
		If ($My.Log.Length -gt 0) {Add-content $Location $Divider}
`

**Comment by iRon7** [comment]
Ravynne, thanks for the feedback.
I have implemented your feedback in version 02.01.07
