### ISSUE TITLE
Please License This Framework

### ISSUE THREAD

**Issue by geek0x23** [iRon7/Log-Entry#5]
This project looks awesome and I'd love to use it, but I have one (hopefully simple) question.  Can you provide a license for this project?  Right now, I don't see a license mentioned anywhere in the source.  

Obviously the choice of providing a license (or not) is solely yours, but some companies (mine included) will be unable to use this code without one.  If that's your intention, fair enough.  I just thought I'd point it out.

Cheers!

**Comment by iRon7** [comment]
Thanks for the hint, I have added a license to the project.
FYI, I am busy with a new a log _module_ based on the same ideas as in this framework which I hope to be able to release soon.
